spring:
  # 项目名称，默认情况下Nacos中配置需要和这个保持一致
  application:
    name: provider

  # mysql 属性配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?allowMultiQueries=true&characterEncoding=utf8&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    #    password: ENC(VhAJJwXY86SEI+b0tY5eJxhZTDsTLpBv1OT5lmFsuSfy4UuPvV06npnGbdkqYjgp)
    password: 123456
    database: 15

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

server:
  port: 9090
  tomcat:
    threads:
      max: 1000
      min-spare: 10
    max-http-form-post-size: -1 # 解除tomcat上传文件的大小限制，在Springmvc中进行控制
    uri-encoding: utf-8

upload:
  mode: RANDOM_ACCESS
  executor:
    queue-max-size: 20
  block:
    queue-size: 50
  root:
    dir: temp
  window:
    root: D:\\
  chunkSize: 2

#jasypt:
#  encryptor:
#    password: 2Z5zjMEu7o1smsVL
